#' Parameters used in multiple functions
#'
#' @description Reused parameter definitions are gathered here for easier usage.
#'
#' @param bDebug `logical` Print debug messages? Default: `FALSE`.
#' @param dfBounds `data.frame` Set of predicted percentages/rates and upper-
#'   and lower-bounds across the full range of sample sizes/total exposure
#'   values for reporting. Created by passing `dfResults` and `dfMetrics` to
#'   `gsm.reporting::MakeBounds()`. Expected columns: `Threshold`, `Denominator`,
#'   `Numerator`, `Metric`, `MetricID`, `StudyID`, `SnapshotDate`.
#' @param dfGroups `data.frame` Group-level metadata dictionary. Created by
#'   passing CTMS site and study data to `gsm.mapping::MakeLongMeta()`. Expected
#'   columns: `GroupID`, `GroupLevel`, `Param`, `Value`.
#' @param dfMetrics `data.frame` Metric-specific metadata for use in charts and
#'   reporting. Created by passing an `lWorkflow` object to
#'   `gsm.reporting::MakeMetric()`. Expected columns: `File`, `MetricID`,
#'   `Group`, `Abbreviation`, `Metric`, `Numerator`, `Denominator`, `Model`,
#'   `Score`, and `Threshold`. For more details see the Data Model vignette:
#'   `vignette("DataModel", package = "gsm.core")`.
#' @param dfResults `data.frame` A stacked summary of analysis pipeline output.
#'   Created by passing a list of results returned by `gsm.core::Summarize()` to
#'   `gsm.reporting::BindResults()`. Expected columns: `GroupID`, `GroupLevel`,
#'   `Numerator`, `Denominator`, `Metric`, `Score`, `Flag`, `MetricID`,
#'   `StudyID`, `SnapshotDate`.
#' @param lMetric `list` Metric-specific metadata for use in charts and
#'   reporting. Created by passing an `lWorkflow` object to
#'   `gsm.reporting::MakeMetric()` and turning it into a list. Expected columns:
#'   `File`,`MetricID`, `Group`, `Abbreviation`, `Metric`, `Numerator`,
#'   `Denominator`, `Model`, `Score`, and `strThreshold`. For more details see the
#'   Data Model vignette: `vignette("DataModel", package = "gsm.core")`.
#' @param strOutputLabel `character` Label describing the output object, which is assigned to the
#'   `output_label` attribute of the output object and appears in the report generated by
#'   `gsm.kri::Report_KRI()`.
#' @param vOutcomeOptions `character` Vector of outcome options for the y-axis dropdown.
#'   Default: `c("Score", "Metric", "Numerator")`. Must include `strOutcome`.
#'
#' @name shared-params
#' @keywords internal
NULL
